### ISSUE TITLE
Feedback ?

### ISSUE THREAD

**Issue by aschelch** [Uralstech/vid-orca#1]
Hi,

Did you have some feedback about response time ? 

Today I used your repo to deploy it myself on GCP. But even with llama-2-7b.ggmlv3.q4_K_S.bin and 16Gb RAM and 4 vCPU. It's quite slow.

Note: I just had to change to use `python:3.11-slim-bullseye` to avoid an error while building the image.

Thanks for your repo thought ;)

**Comment by Uralstech** [comment]
Thanks for checking out my repo!

Yes, it is quite slow, compared to GPT-3.5. The problem with Cloud Run is that it does not allow you to use GPUs, which most of these models are meant to run on. I am looking into GKE, which lets you use GPUs.

About the Dockerfile issue, I did sometimes get errors when building the image - around the package installation step - but building it again seemed to fix it.

**Comment by Uralstech** [comment]
For those viewing this in the future:
The wiki now explains how to deploy to Google Compute Engine, which has GPUs.

<https://github.com/Uralstech/vid-orca/wiki/LLaMA-On-Google-Compute-Engine>
