### ISSUE TITLE
Fastapi llama 27b cht q2

### ISSUE THREAD

**Issue by katniss20** [Uralstech/vid-orca#2]
Hi i am new to llama and my computer cant run my fastapi as it took long to response. So i decided to deploy my fastapi with model llama 2 7b chat to app engine but it got error 502. I dont know where is the problem as i cant run it locally. So can you help me. And this is my code : 

import copy
from fastapi import FastAPI, HTTPException
from llama_cpp import Llama
from pydantic import BaseModel
# loading model
print("loading model...")
llm = Llama(model_path=r"C:\Users\johnh\PycharmProjects\pythonProject1\models\llama-2-7b-chat.Q2_K.gguf")
print("model loaded!")

app = FastAPI()

class InputMessage(BaseModel):
    message: str

class OutputMessage(BaseModel):
    response: str

@app.get("/")
def read_root():
    return {"message": "Welcome to the chatbot API!"}

@app.post("/chat", response_model=OutputMessage)
def chat_post(input_message: InputMessage):
    try:
        global llm
        if llm is None:
            raise HTTPException(status_code=500, detail="Chatbot model not loaded")

        user_message = input_message.message

        # Use your chatbot model to generate a response
        bot_response_dict = llm(user_message,
                                max_tokens=-1,
                                echo=False,
                                temperature=0.1,
                                top_p=0.9)

        # Extract the response from the dictionary
        bot_response = bot_response_dict.get('response', 'Default response')

        # Print the response content to the console
        print(f"bot_response_dict: {bot_response_dict}")

        return OutputMessage(response=bot_response)
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

**Comment by Uralstech** [comment]
Hi! Thanks for checking out my repo!

This seems to be a problem regarding Google Cloud, so I checked what error 502 means:
> An error code 502 with BAD_GATEWAY in the message usually indicates that App Engine terminated the application because it ran out of memory. The default App Engine flexible VM only has 1GB of memory, with only 600MB available for the application container. [1]

You will probably have to increase the memory of the VM. Assuming you are using Llama-2-7B-Chat-GGML, the maximum required ram for the q2_K model is 5.37 GB [2].

**Sources:**
[1] [*Troubleshooting response errors - Error code 502 or 503*](https://cloud.google.com/endpoints/docs/openapi/troubleshoot-response-errors#error_code_502_or_503)
[2] [*TheBloke/Llama-2-7B-Chat-GGML*](https://huggingface.co/TheBloke/Llama-2-7B-Chat-GGML#provided-files)
